name: kzsaa . ci

on:
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load Configuration
        uses: falti/dotenv-action@v1.0.4
        id: config
        with:
          path: config.env

      - name: Check Configuration
        run: |
          function required () { if ! [[ "$1" ]]; then echo "$2 variable can't be null." && exit 1; fi }
          required "${{ steps.config.outputs.BOT_TOKEN }}" "BOT_TOKEN config"
          required "${{ steps.config.outputs.CHAT_ID }}" "CHAT_ID config"
          required "${{ steps.config.outputs.LINK_FILE_TO_SEND }}" "LINK_FILE_TO_SEND config"
          required "${{ steps.config.outputs.FILE_PATH }}" "FILE_PATH config"
          required "${{ steps.config.outputs.TEXT_TO_SEND }}" "TEXT_TO_SEND config"
          
      - name: Setup Initializing
        run: |
          sudo apt-get install -y git wget git zip unzip curl axel aria2
          
      - name: Downloading File To Upload
        run: |
         echo "Downloading File From UrL"
         echo "Using Aria2c"
         mkdir $GITHUB_WORKSPACE/kzsaaCIup
         cd $GITHUB_WORKSPACE/kzsaaCIup && aria2c "${{ steps.config.outputs.LINK_FILE_TO_SEND }}" 
         
      - name: Uploading File To Telegram Chat
        run: |
          FILE_PATH="${{ steps.config.outputs.FILE_PATH }}"
          CAPTION="${{ steps.config.outputs.TEXT_TO_SEND }}"
          CHAT_ID="${{ steps.config.outputs.CHAT_ID }}"
          
          curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendDocument" \
          -F "chat_id=$CHAT_ID" \
          -F "document=@$FILE_PATH" \
          -F "caption=$CAPTION"
